### ISSUE TITLE
Connects to server, key escrow stalls and fails

### ISSUE THREAD

**Issue by selfcommit** [grahamgilbert/Crypt-Server#11] opened 2015-08-10 22:27 UTC
I've successfully run the client as root from command line, and can see the attempt to contact the crypt server.  Unfortunately the escrow seems to fail quietly, and while the local HDD is successfully setup to use filevault, the crypt client hangs, and no client appears in the crypt server. 

Suggestions on where I can look for logging would be appreciated.

**Comment by grahamgilbert** [comment] 2015-08-10 22:30
Since you don't say how you are running the server nor how you are launching the client, this is guess work:

Have you checked your web server logs?

If the key cannot be escrowed, it is stored in root's home directory. Is it present?

**Comment by selfcommit** [comment] 2015-08-11 00:22
@grahamgilbert  As I'm currently testing the client, I'm kicking it off from the command line as root user. (I obtained the client by generating a build from the client repo)
The only warn I'm seeing in my web logs:
 RuntimeWarning: DateTimeField received a naive datetime (2015-07-30 21:27:01.215370) while time zone support is active
(I've since turned off timezone support)

From the client:
Only noteworthy event from the client:
2015-08-10 19:06:27.714 Crypt[517:6130] unlockFocus called too many times. Called on <NSButton: 0x7fcb94c31980>.
![hidden](https://cloud.githubusercontent.com/assets/1029030/9186523/b356e588-3f93-11e5-883e-e4f31599479c.png)
(The client then hangs at this point)

The Root users home directory is empty, yet filevault is activated once I restart. (OSX 10.10.4

My server environment is Appengine, but I'm confident the config is good, as I was able to successfully escrow 1 time.  (I have yet to determine why the client did not hang on that occasion)

**Comment by arubdesu** [comment] 2015-08-11 00:52
Hey Mr. O'Boyle, I've had a similar symptom, but if the client is successfully rebooting then it's not 'hung'. We've had a slight change in plumbing recently that you must be using a valid cert, so if any seeding in the system keychain is needed please confirm by going to the 'commit' URL in a browser.
There are experts on both App Engine and Crypt that are going to be at MacAdminMonthly tomorrow if you were in Manhattan…

**Comment by selfcommit** [comment] 2015-08-11 01:00
@arubdesu I should be clear - the client does not succewssfully reboot.  I have to force quit and manually reboot. (After reboot Filevault is enabled)  The one successful request looks good in the Appengine console (I've omitted the POST line to /checkin'): 
![image](https://cloud.githubusercontent.com/assets/1029030/9187755/2828b40a-3fa2-11e5-8757-b0fdcf52246d.png)

Which leads me back to the client.  
I'm using the appspot domain, so https traffic should be OK , but it is worth noting the one successful run I had involved pointing the client to http:// rather than https. (That change alone did not create a repeatable solution)

**Comment by arubdesu** [comment] 2015-08-11 01:10
I doubt Graham is using a non-customized version of the client, and had been kicking it off with LoginScriptPlugin as of recently, but it's still pretty tame when it comes to the app side of things. You will see weirdness where curl errors silently unless you crack into an interactive Python session and check your return value, though. That's just for now, if you wanted to join us in [macadmins](macadmins.org) slack in the AM we could talk you through it. 
And that meetup tomorrow will have more info here: http://www.macadminmonthly.org/meetings

**Comment by selfcommit** [comment] 2015-08-11 01:49
@arubdesu  Thanks, I'll add you to my slack channels.  I'll try and join you tomorrow.  

After some digging with my rest client / looking at the django view, I'm confident the server piece is working fine.  I'll sanitize and share my appengine version later for anyone interested.  

I'll likely write my own client with some added flags for missing fdesetup functionality (number of user refusals etc)  I'm happy to share that as well.  

My issue stands that the crypt client is stalling for unknown reasons - I'm happy to provide more information if there's hidden logging available somewhere i'm not looking.

**Comment by grahamgilbert** [comment] 2015-08-12 20:46
I'm not confident the server is fine - I've never run Crypt on app engine, so have no idea what it needs - it's entirely possible that the client doesn't work with app engine. Have you tried on a regular docker host or via apache?

**Comment by selfcommit** [comment] 2015-08-13 02:10
@grahamgilbert  I haven't tried a regular build.  I can say that if I pass what the django view expects via REST client, the objects are saved correctly.  
I'm happy with it at this point - I'll likely put together a python client and fork a "AppEngine" repo with instructions.   

If you're confident the issue is related to Appengine, I'd say we can resolve this.

**Comment by grahamgilbert** [comment] 2015-08-13 05:33
Well I've not seen this - I've seen it when using the login script plugin (instructions are going to revert to using the login hook when I get min), but never when running it in the manner you are.

**Comment by Jimmy-John** [comment] 2015-08-14 19:52
Not to muddy the waters, but it was this exact behavior which kind of stalled our testing of Crypt.  The UI would hang, FileVault would be enabled, and the escrow would never happen.  I noticed that normally when the escrow fails, there is supposed to be a plist saved to /private/var/root, but this was not saved when I checked.  I actually added a massive amount of debugging log output to my version of the client before compiling, unfortunately the logs on that run were lost.  If I remember correctly (heaven forbid), I believe that the escrowKey function was entered, but the escrow_key function was not, indicating that there was some issue with the call to either: 
NSApp.beginSheet_modalForWindow_modalDelegate_didEndSelector_contextInfo_
or
self.progressIndicator.startAnimation_

Anyways, I haven't been able to reproduce the issue in a few days, and every thing has been working fine since then.  Hopefully my input sparks an "Ah ha!" moment, and doesn't exhume a perfectly dead bug.

**Comment by grahamgilbert** [comment] 2015-08-14 19:55
Unfortunately similar code is called in a few places. I'll take a look at
this over the next couple of weeks - but you did give me a good place to
start looking.

**Comment by grahamgilbert** [comment] 2016-01-13 16:13
Closing this, as Crypt2 will be out soon that doesn't have any of this code used.

**Closed by grahamgilbert** 2016-01-13 16:13 UTC

**Comment by Jimmy-John** [comment] 2016-01-13 19:14
Hi Graham,

Sorry I didn't get back to you sooner. We were still experiencing it, but if a new client is coming out, we'll probably just test the new client and see if we continue to see it. It appeared to happen when trying to render the progress bars, but I'm not 100%. 

Jimmy
